### ISSUE TITLE
Not getting .yml file upon downloading Example files

### ISSUE THREAD

**Issue by josenimo** [labsyspharm/cylinter#120]
Dear cylinter developer,

I am really excited to put cylinter to use, I think it is a great idea!
I try downloading the example data, but it seems the yml file is not there, I tried twice in my pc.

`synapse get -r syn25685780 --downloadLocation C:\Users\<username>\Desktop\cylinter_demo --multiThreaded`

Best,
Jose

**Comment by gjbaker** [comment]
Dear Jose,

Thank you for your interest in CyLinter! A template config.yml file can be found in the Python virtual environment generated when the following command is run: python3 -m venv C:\Users\<username>\cylinter. You may have already run this command if you followed the CyLinter installation instructions here: https://labsyspharm.github.io/cylinter/installation/.

Please let me know if I can be of any further assistance.

All the best,
-Greg

**Comment by josenimo** [comment]
Hey Greg, 
Thanks for the quick response, so I am having some problems. I tried following those instructions to create the virtual environment. I had to install python3.8-venv and then run the `python3 -m venv ./cylinter` this worked. However the `activate` command is not found.. Maybe it helps knowing that I am running in an Ubuntu wsl2 in win10. 

Best,
Jose

**Comment by gjbaker** [comment]
Hi Jose,

Based on your updated note, it sounds like you have successfully installed the venv. Did you get an error message when you ran `pip install cylinter`? If so, would you share it?

**Comment by josenimo** [comment]
There was no error message, it finished, I even typed `cylinter -h` and it showed me the help prompt, but from here am I still kinda lost. I have my MCMICRO runs that I would like to test cylinter with. and I more or less understand the input folder structure, but I still cannot find the config.yml file.

**Comment by adajnq** [comment]
Hello, I have followed the installation instructions and I am experiencing the same problem of not finding the yml file within the virtual environment
