### ISSUE TITLE
Compatibility with ubuntu?

### ISSUE THREAD

**Issue by aandytu** [labsyspharm/cylinter#129]
I have recently started using some modules on mcmicro, with decent amount of success, and I'm wondering if cylinter is compatible with ubuntu desktop?

I'm hoping to run this on a google cloud vm (to obviate the need to move images to local), and on it I can run a ubuntu desktop instance.

**Comment by gjbaker** [comment]
Hi aandytu,

Thank you for your interest in CyLinter! At this point the program has not been tested on Linux, but I would encourage you to give it a try and let us know about your experience. We are always looking for ways to improve and expand access to the program. I would suggest downloading the small example dataset from Sage Synapse initially (instructions for how to do so can be found on the CyLinter website: https://labsyspharm.github.io/cylinter/exemplar/). This would make for the most straight forward test to determine whether the program is compatible with your compute infrastructure. Regarding access to remote data, we routinely access data stored on the high-performance computer cluster here at HMS for CyLinter analysis on local machines, so this may be an alternative to running a virtual machine in the cloud. Let us know how it goes!

-Greg and the CyLinter team

**Comment by jmuhlich** [comment]
We have an experimental conda package up on our conda channel. Install using this command:
`conda install -c conda-forge -c labsyspharm cylinter`
Note that this currently takes quite a long time to install. If you first install mamba from the conda-forge channel and use that to install (`mamba install ...`) it will complete much faster.

**Comment by aandytu** [comment]
Thanks! I decided to just test the program locally on my laptop. I am testing oust using `macFuse` to mount our gcp buckets, but i'm not entirely confident that the data will stream quickly enough. Even downloading the example data into the mounted volume was difficult.

Are there more resources (papers, videos, etc.) that can take me through running the different modules of cylinter? I'm analyzing CODEX/Phenocycler data. I can tell that there are a lot of different modules each designed to tackle a different artifacts, but I'm struggling to understand the basic concepts behind them.

**Comment by gjbaker** [comment]
Hi aandytu! We aim to have a preprint out in the coming weeks that will have more details. In the meantime, you can take a look at the docs for the individual modules here: https://labsyspharm.github.io/cylinter/modules/.
