### ISSUE TITLE
conda dependency resolution is slow

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/cylinter#131]
As we explore packaging for conda, one problem we've encountered is very slow dependency resolution for our large set of dependencies. Using mamba instead of conda helps of course, but we should explore whether there are ways to optimize the dependency list itself. A StackOverflow comment on this general issue at https://stackoverflow.com/a/71405930 suggests the following:
> At least pin the python version, e.g., python=3.9. Consider also adding minimum versions for DAG "hubs" like numpy, pandas, etc.. This would vastly reduce the solution space.

**Comment by aandytu** [comment]
tagging on this: I noticed that mamba doesn't quite solve all the dependencies automatically. It complains that some of the packages are not available anywhere, despite the fact that they are available via conda-forge. I manually installed them one-by-one, and cylinter was installed successfully, entirely using mamba/conda.

**Comment by gjbaker** [comment]
Thank you for commenting, aandytu!

We have had success in installing the program using a single conda/mamba command by specifying both "-c conda-forge" and "-c labsyspharm", as one of its dependencies called "cellcutter" is currently only available on the labsyspharm channel.

This command should create a dedicated conda environment (called cylinter) and install the program in one command: mamba create -n cylinter -c conda-forge -c labsyspharm cylinter

-Greg

**Comment by gjbaker** [comment]
Closing this issue, as we have moved to Libmamba as a fast and reliable dependency solver for Conda. Instructions for installing CyLinter via this method are available here: https://labsyspharm.github.io/cylinter/installation/
