### ISSUE TITLE
Deprecated version 0.0.44 installed

### ISSUE THREAD

**Issue by MDHowe4** [labsyspharm/cylinter#171]
Hello,

Fantastic tool that I am certain will be of use for our group as we try to improve our spatial pipeline qc, however, we had quite a few issues with installing and running on the example data. Following the installation guide https://labsyspharm.github.io/cylinter/installation/ here installs version 0.0.44 which throws errors and causes other issues with the Example data syn52859560 and ultimately doesn't work as expected. I believe there are also deprecated config options from 0.0.44 that are incompatible with the example datas `config.yml`. Our short term solution was to install cellcutter from labsyspharm and install cylinter from `pyproject.toml`. Steps for reproduction:

`mamba create -n cylinter -c labsyspharm python=3.11 cellcutter`
`mamba activate cylinter`
`pip install -e .` with these specific packages commented out and `matplotlib = "*"` commented in.

![1](https://github.com/labsyspharm/cylinter/assets/115341984/03ea4bc4-939d-485b-9714-a801b687b998)

![2](https://github.com/labsyspharm/cylinter/assets/115341984/a5721dfe-ecde-4a0c-83d5-703c6ddb05a9)

Which installed v0.0.47 which worked perfectly with the Example data. I believe the channels will need to be updated with the newest version for compatibility with the example docs.

**Comment by jmuhlich** [comment]
Could you please run `conda config --show > conda-config.txt` and upload the resulting conda-config.txt file here? Thanks.

**Comment by gjbaker** [comment]
To avoid confusion with older versions, the CyLinter installation command (found here: https://labsyspharm.github.io/cylinter/installation/) now explicitly specifies the current version (v0.0.47) for download.
