### ISSUE TITLE
No pip install Instructions

### ISSUE THREAD

**Issue by DarioS** [labsyspharm/cylinter#195]
[CyLinter is available from PyPi](https://pypi.org/project/cylinter/) but the user guide has no instructions about using `pip install`.

**Comment by gjbaker** [comment]
Dear DarioS,

Thank you for your interest in CyLinter! Installation via pip is now deprecated. Please follow the instructions at the CyLinter website (https://labsyspharm.github.io/cylinter/installation/) for conda installation of the current version (v0.0.49).

-Greg
